version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "8000:8000"
    env_file:
      - env/.env.production
    depends_on:
      - redis

  redis:
    image: redis:7
    volumes:
      - redis_data_prod:/data

volumes:
  redis_data_prod: