# Generated by Django 5.1.2 on 2024-11-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_broker_ref',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('broker', 'user_broker_ref')},
        ),
    ]
