name: Test CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    services:
      #Sets postgres service to run integration tests
      postgres:
        image: postgres:13
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: portfoliouser
          POSTGRES_PASSWORD: dummypassword
          POSTGRES_DB: portfoliodb

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install Dependencies
      run: |
        poetry install --no-interaction --no-ansi

    - name: Run Tests
      env:
        # Set Django's settings module for pytest
        DJANGO_SETTINGS_MODULE: portfolio.settings
        DATABASE_URL: postgres://portfoliouser:dummypassword@localhost:5432/portfoliodb
      run: |
        poetry run pytest